# Site settings
author: LaRaye 
title: Code Life
header-img: img/home-bg.png
email: lnj2105@gmail.com
copyright_name: LaRaye 
description: > # this means to ignore newlines until "baseurl:"
  The Highs and Lows of Learning to Program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  LaRaye

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
